ECOMENGG-3305: Added proxy redirection Urls for Shopify Integration
cb-ashik/bc-proxy-server pull request #1
Opened 2021-04-30 12:22 UTC by cb-shubhamraut

Hi,

Modified file add Redirection Urls for Shopify integrations. As, we don't have push access to bc-proxy-server, I have forked the repo.

2021-04-30 12:36 UTC, cb-rajat requested changes

2021-04-30 12:36 UTC, cb-rajat commented on webpack.config.js
> +	    '/shopify/webhookseg': {
Is it required if `'*'` rule is already present?

2021-04-30 12:36 UTC, cb-rajat commented on webpack.config.js
> +                target: 'http://app.integrations.localcb.in:9090',
Change to `http://app.localcb.in:9090` in all places.

2021-04-30 12:36 UTC, cb-rajat commented on webpack.config.js
> +                // pathRewrite: { '/proxy/bigcommerce/uninstall': '/bigcommerce/uninstall' },
Remove all commented code.

2021-04-30 18:08 UTC, cb-shubhamraut commented on webpack.config.js
> +	    '/shopify/webhookseg': {
I tried testing this. without (/shopify/webhookseg), This will be picked up by shopify/*. So we would need this.

2021-04-30 18:09 UTC, cb-shubhamraut commented on webpack.config.js
> +                target: 'http://app.integrations.localcb.in:9090',
> Change to `http://app.localcb.in:9090` in all places.

Chaged to `http://app.localcb.in:9090` in all places.

2021-05-03 05:09 UTC, cb-priya approved these changes

2021-06-14 12:03 UTC, merged